baseURL = "https://example.com"

languageCode = "en-us"
DefaultContentLanguage = "zh-cn"
title = "Bifrost Document"
theme = "hugo-theme-techdoc"

hasCJKLanguage = true
metaDataFormat = "yaml"

pygmentsCodeFences = true
pygmentsUseClasses = true

defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false

[Params]

    # Souce Code repository section
    description = "Bifrost ---- 面向生产环境的 MySQL 同步到 Redis,MongoDB 等服务的异构中间件"
    github_repository = "https://github.com/brokercap/Bifrost"
    version = "1.1.0"

    # Documentation repository section
    # documentation repository (set edit link to documentation repository)
    github_doc_repository = "https://github.com/brokercap/brokercap.github.io"

    # Analytic section
    google_analytics_id = "" # Your Google Analytics tracking id
    tag_manager_container_id = "" # Your Google Tag Manager container id
    google_site_verification = "" # Your Google Site Verification for Search Console

    # Theme settings section
    # Theme color
    custom_font_color = ""
    custom_background_color = ""

    # Documentation Menu section
    # Menu style settings
    menu_style = "open-menu" # "open-menu" or "slide-menu"

    # Date format
    dateformat = "" # default "2 Jan 2006"
    # See the format reference https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference

    # path name excluded from documentation menu
    menu_exclusion = [
        "archives",
        "archive",
        "blog",
        "entry",
        "post",
        "posts"
    ]

# Global menu section
[[menu.main]]
    name = "首页"
    url = "http://www.xbifrost.com"
    weight = 1

[[menu.main]]
    name = "Github"
    url = "https://github.com/brokercap/Bifrost"
    weight = 2

[[menu.main]]
    name = "Gitee"
    url = "https://gitee.com/jc3wish/Bifrost"
    weight = 3

[[menu.main]]
    name = "版本差异"
    url = "https://github.com/brokercap/Bifrost/blob/master/changelog.txt"
    weight = 4

[[menu.main]]
    name = "作者博客"
    url = "https://jc3wish.github.io"
    weight = 5

[[menu.main]]
    name = "联系我们"
    url = "/other/contact_us/"
    weight = 6

[[menu.main]]
    name = "捐赠"
    url = "/other/donate/"
    weight = 7

